#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_08_25   Slot: 4.2   GPUs: [4, 5, 6, 7]
# Delegates to the semantic experiment script; GPU assignment lives in its YAML gpu_ids.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
exec bash "${REPO_ROOT}/scripts/fdrr/run_B_fdrr_train_sample_eval.sh"
