#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_06_21   Slot: 1.2   GPUs: [4, 5, 6, 7]
# Delegates to the semantic experiment script; GPU assignment lives in its YAML gpu_ids.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
exec bash "${REPO_ROOT}/scripts/proto_t/run_B_tc_proto_t_direct_v2_train_sample_eval.sh"
