#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_08_28   Slot: 2.1   GPUs: [0, 1, 2, 3]
# Delegates to the semantic experiment script; GPU assignment lives in its YAML gpu_ids.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
exec bash "${REPO_ROOT}/scripts/phase_metric/run_B_phase_metric_shuffle_train_sample_eval.sh"
