#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_09_21   Slot: 2.4   GPUs: [6, 7]
# Delegates to the semantic experiment script; GPU assignment lives in its YAML gpu_ids.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
exec bash "${REPO_ROOT}/scripts/dualreg/run_B_dualreg_lsoff_lam3p0_train_sample_eval.sh"
