#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_08_05   Slot: 6.1   GPUs: [0, 1]
# Delegates to the semantic experiment script; GPU assignment lives in its YAML gpu_ids.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CONFIG_PATH="${REPO_ROOT}/configs/004_ProMoE_B_expert_contra_param_shared_uncond.yaml"
if ! grep -Fqx 'gpu_ids: [0, 1]' "${CONFIG_PATH}"; then
  echo "ERROR: historical launcher slot [0, 1] does not match ${CONFIG_PATH}; refusing to start and risk a GPU collision." >&2
  echo "The config is currently reserved by the fresh 4-GPU补测队列." >&2
  exit 2
fi
exec bash "${REPO_ROOT}/scripts/expert_contra/run_B_expert_contra_param_shared_uncond_train_sample_eval.sh"
