#!/usr/bin/env bash
# Auto-generated by scripts/_run_times/new_run.sh
# Date group: 2026_10_03   GPUs needed: 2
# Claims 2 idle GPU(s) in id order and hands them to the semantic script,
# so this runs unchanged on a 4-GPU or an 8-GPU machine.  A GPU counts as idle
# when its used memory is under PROMOE_GPU_IDLE_MAX_MIB (100 by default, which
# ignores the few MiB of driver residue an unused card reports) and no live
# claim holds it.  Set PROMOE_GPU_IDS_OVERRIDE yourself to pick GPUs by hand.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
source "${REPO_ROOT}/scripts/_run_times/claim_gpus.sh"

if [[ -z "${PROMOE_GPU_IDS_OVERRIDE:-}" ]]; then
    # Call it directly, never via $( ): in a subshell the EXIT trap would
    # release the claim before the trainer ever starts.
    promoe_claim_gpus 2
    export PROMOE_GPU_IDS_OVERRIDE="${PROMOE_CLAIMED_GPUS}"
fi
echo "[$(date '+%H:%M:%S')] B_regcombo_gc_ls0p05_param_b4_tau0p7: using GPU(s) ${PROMOE_GPU_IDS_OVERRIDE}"
exec bash "${REPO_ROOT}/scripts/regcombo/run_B_regcombo_gc_ls0p05_param_b4_tau0p7_train_sample_eval.sh"
